version: '3.8'
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
    user: 1000:1000
    #network_mode: host

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    #  - /dev/pts/:/dev/pts/
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    user: 1000:1000
    group_add:
      - dialout
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    #network_mode: host
